{"name": "test_invalid_mobile_number_login_details[8348897565-We cannot find an account with that mobile number]", "status": "passed", "parameters": [{"name": "username", "value": "'8348897565'"}, {"name": "expected", "value": "'We cannot find an account with that mobile number'"}], "start": 1707709105034, "stop": 1707709108177, "uuid": "7ff82e85-6127-4ee4-a46a-c835f2c174f6", "historyId": "a4146c86598264bdabcb4f6fda2be33b", "testCaseId": "d24cb168c92779c88be90a2810ee7f46", "fullName": "test_validating_login_page_details#test_invalid_mobile_number_login_details", "labels": [{"name": "suite", "value": "test_validating_login_page_details"}, {"name": "host", "value": "vikas-Mi-NoteBook-Pro"}, {"name": "thread", "value": "3866-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_validating_login_page_details"}]}