{"name": "test_invalid_mobile_number_login_details[8348-We cannot find an account with that mobile number]", "status": "passed", "parameters": [{"name": "username", "value": "'8348'"}, {"name": "expected", "value": "'We cannot find an account with that mobile number'"}], "start": 1707709101149, "stop": 1707709104587, "uuid": "eae971c9-cd66-4dfe-9cd1-b6736fbef04e", "historyId": "68c24b9ce36202e0d12c7de29820b69d", "testCaseId": "d24cb168c92779c88be90a2810ee7f46", "fullName": "test_validating_login_page_details#test_invalid_mobile_number_login_details", "labels": [{"name": "suite", "value": "test_validating_login_page_details"}, {"name": "host", "value": "vikas-Mi-NoteBook-Pro"}, {"name": "thread", "value": "3866-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_validating_login_page_details"}]}